# Generated by Django 5.1.6 on 2025-02-07 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('last_analyzed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OverallScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repo_analyzer.repository')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('details', models.JSONField()),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo_analyzer.repository')),
            ],
        ),
    ]
